In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import BallTree

In [2]:
import pandas as pd
import numpy as np
from sklearn.neighbors import BallTree

In [3]:
# Bellevue sample coordinates
df = pd.DataFrame({
    "lat": [
        47.6101,
        47.6112,
        47.6123,
        47.6135,
        47.6140,
        47.6152,
        47.6161,
        47.6174,
        47.6182,
        47.6191,
        47.6200
    ],
    "long": [
        -122.2015,
        -122.2021,
        -122.2030,
        -122.2040,
        -122.2051,
        -122.2063,
        -122.2074,
        -122.2080,
        -122.2091,
        -122.2102,
        -122.2110
    ]
})

df.head()

,lat,long
0,47.6101,-122.2015
1,47.6112,-122.2021
2,47.6123,-122.2030
3,47.6135,-122.2040
4,47.6140,-122.2051


In [4]:
coords = np.radians(df[["lat", "long"]])

tree = BallTree(coords, metric="haversine")

distances, indices = tree.query(coords, k=10)

In [5]:
# Convert radians to kilometres
distances_km = distances * 6371

print("Neighbour indices")
print(indices)

print()

print("Distances (km)")
print(distances_km)

Neighbour indices
[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  0  2  3  4  5  6  7  8  9]
 [ 2  1  3  4  0  5  6  7  8  9]
 [ 3  4  2  5  1  6  0  7  8  9]
 [ 4  3  5  2  6  1  7  0  8  9]
 [ 5  6  4  3  7  8  2  9  1 10]
 [ 6  5  7  8  4  3  9 10  2  1]
 [ 7  8  6  9  5 10  4  3  2  1]
 [ 8  7  9 10  6  5  4  3  2  1]
 [ 9 10  8  7  6  5  4  3  2  1]
 [10  9  8  7  6  5  4  3  2  1]]

Distances (km)
[[0.         0.13032214 0.26923413 0.42196228 0.5107708  0.67161042
  0.80044604 0.94672727 1.06572274 1.19448301]
 [0.         0.13032214 0.13968705 0.29273283 0.38406834 0.54492972
  0.67431634 0.81906886 0.93870506 1.0678449 ]
 [0.         0.13968705 0.15304799 0.24599342 0.26923413 0.4064156
  0.53602296 0.6797516  0.79966794 0.92897127]
 [0.         0.09944819 0.15304799 0.25584397 0.29273283 0.38540184
  0.42196228 0.52721691 0.64750552 0.77699042]
 [0.         0.09944819 0.16092096 0.24599342 0.29025695 0.38406834
  0.43609957 0.5107708  0.55497812 0.68390612]
 [0.         0.12966674 0.16

In [6]:
print("Maximum neighbour distance:",
      round(distances_km.max(), 2),
      "km")

Maximum neighbour distance: 1.19 km


## Validation

The Bellevue sample confirms that the BallTree KNN graph correctly
identifies the nearest neighbours.

For K=10, all neighbouring properties lie within approximately
2 kilometres, validating the spatial graph construction.

In [7]:
coords = np.radians(df[["lat", "long"]])

tree = BallTree(coords, metric="haversine")

distances, indices = tree.query(coords, k=10)

In [8]:
# Convert radians to kilometres
distances_km = distances * 6371

print("Neighbour Indices")
print(indices)

print("\nDistances (km)")
print(distances_km)

Neighbour Indices
[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  0  2  3  4  5  6  7  8  9]
 [ 2  1  3  4  0  5  6  7  8  9]
 [ 3  4  2  5  1  6  0  7  8  9]
 [ 4  3  5  2  6  1  7  0  8  9]
 [ 5  6  4  3  7  8  2  9  1 10]
 [ 6  5  7  8  4  3  9 10  2  1]
 [ 7  8  6  9  5 10  4  3  2  1]
 [ 8  7  9 10  6  5  4  3  2  1]
 [ 9 10  8  7  6  5  4  3  2  1]
 [10  9  8  7  6  5  4  3  2  1]]

Distances (km)
[[0.         0.13032214 0.26923413 0.42196228 0.5107708  0.67161042
  0.80044604 0.94672727 1.06572274 1.19448301]
 [0.         0.13032214 0.13968705 0.29273283 0.38406834 0.54492972
  0.67431634 0.81906886 0.93870506 1.0678449 ]
 [0.         0.13968705 0.15304799 0.24599342 0.26923413 0.4064156
  0.53602296 0.6797516  0.79966794 0.92897127]
 [0.         0.09944819 0.15304799 0.25584397 0.29273283 0.38540184
  0.42196228 0.52721691 0.64750552 0.77699042]
 [0.         0.09944819 0.16092096 0.24599342 0.29025695 0.38406834
  0.43609957 0.5107708  0.55497812 0.68390612]
 [0.         0.12966674 0.16

In [9]:
print(f"Maximum neighbour distance: {distances_km.max():.2f} km")

if distances_km.max() < 2:
    print("✅ Validation Passed: All K=10 neighbours are within 2 km.")
else:
    print("⚠️ Some neighbours are farther than 2 km.")

Maximum neighbour distance: 1.19 km
✅ Validation Passed: All K=10 neighbours are within 2 km.


## Validation

The Bellevue sample confirms that the BallTree KNN graph correctly
identifies neighbouring properties.

For K=10, the neighbours are expected to lie within approximately
2 kilometres, validating the graph construction.

In [10]:
import folium

# Center map on Bellevue sample
center = [df["lat"].mean(), df["long"].mean()]

m = folium.Map(
    location=center,
    zoom_start=14
)

In [11]:
for _, row in df.iterrows():
    folium.CircleMarker(
        location=[row["lat"], row["long"]],
        radius=5,
        color="blue",
        fill=True,
        fill_opacity=0.7,
    ).add_to(m)

m

In [12]:
for i in range(len(df)):
    for neighbour in indices[i][1:]:   # Skip self

        folium.PolyLine(
            locations=[
                [df.iloc[i]["lat"], df.iloc[i]["long"]],
                [df.iloc[neighbour]["lat"], df.iloc[neighbour]["long"]]
            ],
            color="red",
            weight=1.5,
            opacity=0.6
        ).add_to(m)

m

In [13]:
m.save("reports/figures/knn_graph_map.html")

print("Map saved successfully.")

Map saved successfully.


In [14]:
import pandas as pd
import numpy as np

from sklearn.neighbors import NearestNeighbors

import matplotlib.pyplot as plt

In [15]:
df = pd.read_csv("../data/raw/kc_house_data.csv")

df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503


In [16]:
coords = df[["lat", "long"]]

coords.head()

,lat,long
0,47.5112,-122.257
1,47.7210,-122.319
2,47.7379,-122.233
3,47.5208,-122.393
4,47.6168,-122.045


In [17]:
K = 10

knn = NearestNeighbors(
    n_neighbors=K,
    metric="euclidean"
)

knn.fit(coords)

,"n_neighbors n_neighbors: int, default=5Number of neighbors to use by default for :meth:`kneighbors` queries.",10
,"metric metric: str or callable, default='minkowski'Metric to use for distance computation. Default is ""minkowski"", whichresults in the standard Euclidean distance when p = 2. See thedocumentation of `scipy.spatial.distance<https://docs.scipy.org/doc/scipy/reference/spatial.distance.html>`_ andthe metrics listed in:class:`~sklearn.metrics.pairwise.distance_metrics` for valid metricvalues.If metric is ""precomputed"", X is assumed to be a distance matrix andmust be square during fit. X may be a :term:`sparse graph`, in whichcase only ""nonzero"" elements may be considered neighbors.If metric is a callable function, it takes two arrays representing 1Dvectors as inputs and must return one value indicating the distancebetween those vectors. This works for Scipy's metrics, but is lessefficient than passing the metric name as a string.",'euclidean'
,"radius radius: float, default=1.0Range of parameter space to use by default for :meth:`radius_neighbors`queries.",1.0
,"algorithm algorithm: {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'Algorithm used to compute the nearest neighbors:- 'ball_tree' will use :class:`BallTree`- 'kd_tree' will use :class:`KDTree`- 'brute' will use a brute-force search.- 'auto' will attempt to decide the most appropriate algorithm based on the values passed to :meth:`fit` method.Note: fitting on sparse input will override the setting ofthis parameter, using brute force.",'auto'
,"leaf_size leaf_size: int, default=30Leaf size passed to BallTree or KDTree. This can affect thespeed of the construction and query, as well as the memoryrequired to store the tree. The optimal value depends on thenature of the problem.",30
,"p p: float (positive), default=2Parameter for the Minkowski metric fromsklearn.metrics.pairwise.pairwise_distances. When p = 1, this isequivalent to using manhattan_distance (l1), and euclidean_distance(l2) for p = 2. For arbitrary p, minkowski_distance (l_p) is used.",2
,"metric_params metric_params: dict, default=NoneAdditional keyword arguments for the metric function.",None
,"n_jobs n_jobs: int, default=NoneThe number of parallel jobs to run for neighbors search.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details.",None
Name,Type,Value
effective_metric_ effective_metric_: strMetric used to compute distances to neighbors.,str,'eu...an'
effective_metric_params_ effective_metric_params_: dictParameters for the metric used to compute distances to neighbors.,dict,{}


In [18]:
distances, indices = knn.kneighbors(coords)

In [19]:
print(distances.shape)
print(indices.shape)

(21613, 10)
(21613, 10)


In [20]:
print("Neighbour indices")

print(indices[0])

print()

print("Distances")

print(distances[0])

Neighbour indices
[    0  6320 16895  5809  2382  5407  1634  9101 12623  3882]

Distances
[0.         0.0004     0.0005     0.00100499 0.00104403 0.00208806
 0.00211896 0.00214709 0.00228254 0.0023    ]


In [21]:
sample = pd.DataFrame({
    "Neighbour Index": indices[0],
    "Distance": distances[0]
})

sample

,Neighbour Index,Distance
0,0,0.000000
1,6320,0.000400
2,16895,0.000500
3,5809,0.001005
4,2382,0.001044
5,5407,0.002088
6,1634,0.002119
7,9101,0.002147
8,12623,0.002283
9,3882,0.002300


In [22]:
import sys

sys.path.append("..")

from src.graph.knn_graph import haversine
from src.graph.knn_graph import inverse_distance

In [23]:
lat1 = df.loc[0, "lat"]
lon1 = df.loc[0, "long"]

lat2 = df.loc[1, "lat"]
lon2 = df.loc[1, "long"]

distance = haversine(
    lat1,
    lon1,
    lat2,
    lon2
)

print(distance)

23.787076791429758


In [24]:
weight = inverse_distance(distance)

print(weight)

0.042039632138433154


In [25]:
weights = []

for i in range(10):

    d = haversine(
        df.loc[0, "lat"],
        df.loc[0, "long"],
        df.loc[indices[0][i], "lat"],
        df.loc[indices[0][i], "long"]
    )

    weights.append(inverse_distance(d))

weights

[1000000.0,
 22.482534672368708,
 17.986108612499866,
 13.170734837159465,
 12.16813555458688,
 6.0841193176969535,
 5.910819889060428,
 4.459828323484007,
 5.1622278474922245,
 3.910078650005964]

In [26]:
validation = pd.DataFrame({
    "Neighbour": indices[0],
    "Distance_km": [
        haversine(
            df.loc[0, "lat"],
            df.loc[0, "long"],
            df.loc[idx, "lat"],
            df.loc[idx, "long"]
        )
        for idx in indices[0]
    ],
    "Edge_Weight": weights
})

validation

,Neighbour,Distance_km,Edge_Weight
0,0,0.000000,1000000.000000
1,6320,0.044478,22.482535
2,16895,0.055597,17.986109
3,5809,0.075925,13.170735
4,2382,0.082181,12.168136
5,5407,0.164361,6.084119
6,1634,0.169180,5.910820
7,9101,0.224223,4.459828
8,12623,0.193714,5.162228
9,3882,0.255748,3.910079


In [27]:
sample_index = 0

center_lat = df.loc[sample_index, "lat"]
center_lon = df.loc[sample_index, "long"]

In [28]:
m = folium.Map(
    location=[center_lat, center_lon],
    zoom_start=14
)

In [29]:
folium.Marker(
    [center_lat, center_lon],
    popup="Target House",
    tooltip="Target House",
    icon=folium.Icon(color="red")
).add_to(m)

In [30]:
for idx in indices[sample_index]:

    lat = df.loc[idx, "lat"]
    lon = df.loc[idx, "long"]

    folium.CircleMarker(
        location=[lat, lon],
        radius=5,
        color="blue",
        fill=True,
        fill_opacity=0.7,
        popup=f"House {idx}"
    ).add_to(m)

In [31]:
for idx in indices[sample_index]:

    lat = df.loc[idx, "lat"]
    lon = df.loc[idx, "long"]

    folium.PolyLine(
        [
            [center_lat, center_lon],
            [lat, lon]
        ],
        weight=2
    ).add_to(m)

In [32]:
m

In [35]:
m.save("../reports/maps/knn_graph_sample.html")

In [36]:
import os

print(os.listdir("../reports/maps"))

['knn_graph_sample.html']


In [37]:
num_nodes = len(df)

num_edges = indices.shape[0] * (indices.shape[1] - 1)

avg_degree = num_edges / num_nodes

print("Number of Nodes :", num_nodes)
print("Number of Edges :", num_edges)
print("Average Degree :", avg_degree)

Number of Nodes : 21613
Number of Edges : 194517
Average Degree : 9.0


In [38]:
neighbor_counts = [len(neigh) - 1 for neigh in indices]

print("Minimum Degree :", min(neighbor_counts))
print("Maximum Degree :", max(neighbor_counts))
print("Average Degree :", np.mean(neighbor_counts))

Minimum Degree : 9
Maximum Degree : 9
Average Degree : 9.0
