In [ ]:
import pandas as pd
import numpy as np
from sklearn.neighbors import BallTree

In [2]:
import pandas as pd
import numpy as np
from sklearn.neighbors import BallTree

In [3]:
# Bellevue sample coordinates
df = pd.DataFrame({
    "lat": [
        47.6101,
        47.6112,
        47.6123,
        47.6135,
        47.6140,
        47.6152,
        47.6161,
        47.6174,
        47.6182,
        47.6191,
        47.6200
    ],
    "long": [
        -122.2015,
        -122.2021,
        -122.2030,
        -122.2040,
        -122.2051,
        -122.2063,
        -122.2074,
        -122.2080,
        -122.2091,
        -122.2102,
        -122.2110
    ]
})

df.head()

,lat,long
0,47.6101,-122.2015
1,47.6112,-122.2021
2,47.6123,-122.2030
3,47.6135,-122.2040
4,47.6140,-122.2051


In [4]:
coords = np.radians(df[["lat", "long"]])

tree = BallTree(coords, metric="haversine")

distances, indices = tree.query(coords, k=10)

In [5]:
# Convert radians to kilometres
distances_km = distances * 6371

print("Neighbour indices")
print(indices)

print()

print("Distances (km)")
print(distances_km)

Neighbour indices
[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  0  2  3  4  5  6  7  8  9]
 [ 2  1  3  4  0  5  6  7  8  9]
 [ 3  4  2  5  1  6  0  7  8  9]
 [ 4  3  5  2  6  1  7  0  8  9]
 [ 5  6  4  3  7  8  2  9  1 10]
 [ 6  5  7  8  4  3  9 10  2  1]
 [ 7  8  6  9  5 10  4  3  2  1]
 [ 8  7  9 10  6  5  4  3  2  1]
 [ 9 10  8  7  6  5  4  3  2  1]
 [10  9  8  7  6  5  4  3  2  1]]

Distances (km)
[[0.         0.13032214 0.26923413 0.42196228 0.5107708  0.67161042
  0.80044604 0.94672727 1.06572274 1.19448301]
 [0.         0.13032214 0.13968705 0.29273283 0.38406834 0.54492972
  0.67431634 0.81906886 0.93870506 1.0678449 ]
 [0.         0.13968705 0.15304799 0.24599342 0.26923413 0.4064156
  0.53602296 0.6797516  0.79966794 0.92897127]
 [0.         0.09944819 0.15304799 0.25584397 0.29273283 0.38540184
  0.42196228 0.52721691 0.64750552 0.77699042]
 [0.         0.09944819 0.16092096 0.24599342 0.29025695 0.38406834
  0.43609957 0.5107708  0.55497812 0.68390612]
 [0.         0.12966674 0.16

In [6]:
print("Maximum neighbour distance:",
      round(distances_km.max(), 2),
      "km")

Maximum neighbour distance: 1.19 km


## Validation

The Bellevue sample confirms that the BallTree KNN graph correctly
identifies the nearest neighbours.

For K=10, all neighbouring properties lie within approximately
2 kilometres, validating the spatial graph construction.

In [7]:
coords = np.radians(df[["lat", "long"]])

tree = BallTree(coords, metric="haversine")

distances, indices = tree.query(coords, k=10)

In [8]:
# Convert radians to kilometres
distances_km = distances * 6371

print("Neighbour Indices")
print(indices)

print("\nDistances (km)")
print(distances_km)

Neighbour Indices
[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  0  2  3  4  5  6  7  8  9]
 [ 2  1  3  4  0  5  6  7  8  9]
 [ 3  4  2  5  1  6  0  7  8  9]
 [ 4  3  5  2  6  1  7  0  8  9]
 [ 5  6  4  3  7  8  2  9  1 10]
 [ 6  5  7  8  4  3  9 10  2  1]
 [ 7  8  6  9  5 10  4  3  2  1]
 [ 8  7  9 10  6  5  4  3  2  1]
 [ 9 10  8  7  6  5  4  3  2  1]
 [10  9  8  7  6  5  4  3  2  1]]

Distances (km)
[[0.         0.13032214 0.26923413 0.42196228 0.5107708  0.67161042
  0.80044604 0.94672727 1.06572274 1.19448301]
 [0.         0.13032214 0.13968705 0.29273283 0.38406834 0.54492972
  0.67431634 0.81906886 0.93870506 1.0678449 ]
 [0.         0.13968705 0.15304799 0.24599342 0.26923413 0.4064156
  0.53602296 0.6797516  0.79966794 0.92897127]
 [0.         0.09944819 0.15304799 0.25584397 0.29273283 0.38540184
  0.42196228 0.52721691 0.64750552 0.77699042]
 [0.         0.09944819 0.16092096 0.24599342 0.29025695 0.38406834
  0.43609957 0.5107708  0.55497812 0.68390612]
 [0.         0.12966674 0.16

In [9]:
print(f"Maximum neighbour distance: {distances_km.max():.2f} km")

if distances_km.max() < 2:
    print("✅ Validation Passed: All K=10 neighbours are within 2 km.")
else:
    print("⚠️ Some neighbours are farther than 2 km.")

Maximum neighbour distance: 1.19 km
✅ Validation Passed: All K=10 neighbours are within 2 km.


## Validation

The Bellevue sample confirms that the BallTree KNN graph correctly
identifies neighbouring properties.

For K=10, the neighbours are expected to lie within approximately
2 kilometres, validating the graph construction.